name: 'Poke'
description: 'Sync the GitHub Discussions to a markdown file'
inputs:
  token:
    description: 'A github token for get info'
    default: ${{ github.token }}
  discussionDir:
    description: 'Where you want to store your discussion files'
    default: 'posts'
  pagesDir:
    description: 'Where you want to store your page documentation'
    default: 'pages'
  homePage:
    description: 'The home page location'
    default: 'index.md'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
