name: 'Poke'
description: 'Sync the GitHub Discussions to a markdown file'
inputs:
  token:
    description: 'A github token for get info'
    default: ${{ github.token }}
  type:
    description: 'Which do you want to sync, discussion or comment'
    default: ${{ github.event_name }}
  syncComments:
    description: 'Do you want to sync comments?'
    default: true
  discussionDir:
    description: 'Where you want to store your discussion files'
    default: 'posts'
  commentsDir:
    description: 'Where you want to store your comments'
    default: 'public'

runs:
  using: 'node16'
  main: 'dist/index.js'
